### PR TITLE
add missing LICENSE file

### PR DESCRIPTION
**Pull request by meirwah**
add missing LICENSE file

### CODE REVIEW

**Comment by dgryski** [comment]
The original spooky code was public domain, and so is my implementation. I'd prefer to keep it like that. The license​ file should indicate that or CC0 if that makes your lawyers happier.

**Comment by meirwah** [comment]
ok, so what you want to add to the license file?

**Comment by meirwah** [comment]
you want to use a different license?

**Comment by dgryski** [comment]
n/m, I'll merge MIT because most of my other repos are MIT and the actual license text is shorter.  The relicensing from public domain -> MIT is allowed.

**Comment by meirwah** [comment]
10x!

**Pull request merged**
